#if os(macOS)
import AppKit
import WebKit
import XCTest
@testable import LakeOfFireReader

/// Exercises JavaScript -> WebKit -> actual value decoder, not a synthetic
/// NSDictionary substitute. No external requests or persistent website storage.
final class ReaderContentPayloadWebKitTests: XCTestCase {
    @MainActor
    func testRealWebKitReadabilityKeepsJapaneseTextAndOptionalDefaults() async throws {
        let body = try await receiveJavaScriptBody("""
            ({pageURL: 'https://example.invalid/本', windowURL: 'https://example.invalid/本',
              title: '日本語 📖', byline: '', content: '<ruby>字<rt>じ</rt></ruby>',
              inputHTML: '<p>読む</p>', outputHTML: null})
            """)
        let result = try XCTUnwrap(ReadabilityParsedMessage(body: body))
        XCTAssertEqual(result.title, "日本語 📖")
        XCTAssertEqual(result.byline, "")
        XCTAssertEqual(result.content, "<ruby>字<rt>じ</rt></ruby>")
        XCTAssertEqual(result.inputHTML, "<p>読む</p>")
        XCTAssertEqual(result.outputHTML, "")
    }

    @MainActor
    func testRealWebKitMissingAndWronglyTypedRequiredValuesReject() async throws {
        let body = try await receiveJavaScriptBody("""
            ({unavailable: {pageURL: 0, windowURL: 'https://example.invalid/'},
              readability: {pageURL: 'https://example.invalid/', windowURL: 'https://example.invalid/',
                            title: null, byline: '', content: '<p>読む</p>', inputHTML: ''},
              video: {pageURL: 'https://example.invalid/'},
              metadata: {title: '本', author: '著者', url: false}})
            """)
        let payloads = try XCTUnwrap(body as? [String: Any])
        XCTAssertNil(ReaderModeUnavailableMessage(body: payloads["unavailable"]))
        XCTAssertNil(ReadabilityParsedMessage(body: payloads["readability"]))
        XCTAssertNil(VideoStatusMessage(body: payloads["video"]))
        XCTAssertNil(PageMetadataUpdatedMessage(body: payloads["metadata"]))
    }

    @MainActor
    func testRealWebKitSeparatesCaptionBooleansAndDiagnosticNumericEndpoints() async throws {
        let body = try await receiveJavaScriptBody("""
            ({video: {pageURL: 'https://example.invalid/', windowURL: 'https://example.invalid/',
                      captionsOptions: [false, true, 0, 1].map((flag, i) => ({
                        label: String(i), languageCode: 'ja', kind: 'captions',
                        isAutoGenerated: flag, baseURL: 'https://example.invalid/captions'}))},
              diagnostics: [0, 1, false, true].map(value => ({source: 'https://example.invalid/script.js',
                            documentStartedAtMs: value}))})
            """)
        let payloads = try XCTUnwrap(body as? [String: Any])
        let video = try XCTUnwrap(VideoStatusMessage(body: payloads["video"]))
        XCTAssertEqual(video.captionsOptions.map(\.label), ["0", "1"])
        XCTAssertEqual(video.captionsOptions.map(\.isAutoGenerated), [false, true])
        let diagnostics = try XCTUnwrap(payloads["diagnostics"] as? [Any])
        XCTAssertEqual(diagnostics.compactMap { ReaderOnErrorMessage(body: $0)?.documentStartedAtMilliseconds }, [0, 1])
    }

    @MainActor
    private func receiveJavaScriptBody(_ expression: String) async throws -> Any {
        _ = NSApplication.shared
        let delivered = expectation(description: "WebKit posted a body or reported a navigation failure")
        let receiver = ContentPayloadWebKitReceiver(delivered: delivered)
        let configuration = WKWebViewConfiguration()
        configuration.websiteDataStore = .nonPersistent()
        configuration.userContentController.add(receiver, name: "portPayload")
        let view = WKWebView(frame: CGRect(x: 0, y: 0, width: 320, height: 240), configuration: configuration)
        view.navigationDelegate = receiver
        defer {
            view.stopLoading()
            view.navigationDelegate = nil
            configuration.userContentController.removeScriptMessageHandler(forName: "portPayload")
        }
        view.loadHTMLString("""
            <!doctype html><html><head><meta charset="utf-8"></head><body><script>
            window.webkit.messageHandlers.portPayload.postMessage(\(expression));
            </script></body></html>
            """, baseURL: nil)
        await fulfillment(of: [delivered], timeout: 15)
        if let error = receiver.failure { throw error }
        return try XCTUnwrap(receiver.body)
    }
}

@MainActor
private final class ContentPayloadWebKitReceiver: NSObject, WKScriptMessageHandler, WKNavigationDelegate {
    private let delivered: XCTestExpectation
    private var finished = false
    private(set) var body: Any?
    private(set) var failure: Error?

    init(delivered: XCTestExpectation) { self.delivered = delivered }

    func userContentController(_ userContentController: WKUserContentController, didReceive message: WKScriptMessage) {
        guard !finished else { return }
        finished = true
        body = message.body
        delivered.fulfill()
    }

    func webView(_ webView: WKWebView, didFail navigation: WKNavigation!, withError error: Error) {
        fail(error)
    }

    func webView(_ webView: WKWebView, didFailProvisionalNavigation navigation: WKNavigation!, withError error: Error) {
        fail(error)
    }

    func webViewWebContentProcessDidTerminate(_ webView: WKWebView) {
        fail(NSError(domain: "ReaderContentPayloadWebKitTests", code: 1,
                     userInfo: [NSLocalizedDescriptionKey: "WebKit content process terminated before delivery"]))
    }

    private func fail(_ error: Error) {
        guard !finished else { return }
        finished = true
        failure = error
        delivered.fulfill()
    }
}
#endif
