import Foundation
import XCTest
@testable import LakeOfFireReader

final class ReaderContentPayloadPortTests: XCTestCase {
    private let pageURL = "https://example.invalid/日本語#節"
    private let windowURL = "https://example.invalid/日本語"
    private var urls: [String: Any] { ["pageURL": pageURL, "windowURL": windowURL] }
    private var readability: [String: Any] {
        urls.merging(["title": "日本語の本 📖", "byline": "著者", "content": "<p>読む</p>",
                      "inputHTML": "<html lang='ja'><body>読む</body></html>"]) { _, new in new }
    }
    private var caption: [String: Any] {
        ["label": "日本語", "languageCode": "ja", "kind": "captions", "isAutoGenerated": false,
         "baseURL": "https://example.invalid/captions?language=ja"]
    }
    private var wrongStringValues: [Any] {
        [NSNull(), true, false, 0, 1, 3.5, ["value"], ["value": "text"]]
    }

    func testAllDecodersRejectNonObjectBodies() {
        let bodies: [Any?] = [nil, NSNull(), "text", true, 42, [1, 2], [String](), Data([1])]
        for body in bodies {
            XCTAssertNil(ReaderModeUnavailableMessage(body: body))
            XCTAssertNil(ReadabilityParsedMessage(body: body))
            XCTAssertNil(VideoStatusMessage(body: body))
            XCTAssertNil(PageMetadataUpdatedMessage(body: body))
            XCTAssertNil(ReaderOnErrorMessage(body: body))
        }
    }

    func testModeUnavailableRequiresBothURLStrings() {
        for key in ["pageURL", "windowURL"] {
            var missing = urls
            missing.removeValue(forKey: key)
            XCTAssertNil(ReaderModeUnavailableMessage(body: missing), key)
            for value in wrongStringValues {
                var body = urls
                body[key] = value
                XCTAssertNil(ReaderModeUnavailableMessage(body: body), key)
            }
        }
    }

    func testModeUnavailablePreservesValidURLValues() throws {
        let value = try XCTUnwrap(ReaderModeUnavailableMessage(body: urls))
        XCTAssertEqual(value.pageURL, URL(string: pageURL))
        XCTAssertEqual(value.windowURL, URL(string: windowURL))
    }

    func testReadabilityRequiresEveryRequiredString() {
        for key in ["pageURL", "windowURL", "title", "byline", "content", "inputHTML"] {
            var missing = readability
            missing.removeValue(forKey: key)
            XCTAssertNil(ReadabilityParsedMessage(body: missing), key)
            for value in wrongStringValues {
                var body = readability
                body[key] = value
                XCTAssertNil(ReadabilityParsedMessage(body: body), key)
            }
        }
    }

    func testReadabilityPreservesJapaneseAndHTMLWithoutRewriting() throws {
        let value = try XCTUnwrap(ReadabilityParsedMessage(body: readability))
        XCTAssertEqual(value.title, readability["title"] as? String)
        XCTAssertEqual(value.byline, "著者")
        XCTAssertEqual(value.content, "<p>読む</p>")
        XCTAssertEqual(value.inputHTML, readability["inputHTML"] as? String)
        XCTAssertEqual(value.outputHTML, "")
        XCTAssertEqual(value.pageURL, URL(string: pageURL))
    }

    func testReadabilityPermitsEmptyPresentStrings() throws {
        let body = ["pageURL": "", "windowURL": "", "title": "", "byline": "", "content": "", "inputHTML": ""]
        let value = try XCTUnwrap(ReadabilityParsedMessage(body: body))
        XCTAssertEqual(value.title, "")
        XCTAssertEqual(value.content, "")
        XCTAssertEqual(value.outputHTML, "")
    }

    func testReadabilityOptionalFieldsKeepHotfixDefaults() throws {
        var body = readability
        for key in ["readabilityContainerSelector", "layer0FrameSelector", "layer1ShadowRootSelector",
                    "layer2ShadowRootSelector", "publishedTime", "outputHTML"] { body[key] = NSNull() }
        let value = try XCTUnwrap(ReadabilityParsedMessage(body: body))
        XCTAssertNil(value.readabilityContainerSelector)
        XCTAssertNil(value.readabilityContainerRootSelector)
        XCTAssertNil(value.publishedTime)
        XCTAssertEqual(value.outputHTML, "")
    }

    func testReadabilityPreservesNestedSelectorsAndOutput() throws {
        var body = readability
        body["readabilityContainerSelector"] = "#reader"
        body["layer0FrameSelector"] = "iframe"
        body["layer1ShadowRootSelector"] = "article"
        body["layer2ShadowRootSelector"] = ".content"
        body["publishedTime"] = "2026-09-28"
        body["outputHTML"] = "<ruby>字<rt>じ</rt></ruby>"
        let value = try XCTUnwrap(ReadabilityParsedMessage(body: body))
        XCTAssertEqual(value.readabilityContainerSelector, "#reader")
        XCTAssertEqual(value.readabilityContainerRootSelector?.layer0FrameSelector, "iframe")
        XCTAssertEqual(value.readabilityContainerRootSelector?.layer1ShadowRootSelector, "article")
        XCTAssertEqual(value.readabilityContainerRootSelector?.layer2ShadowRootSelector, ".content")
        XCTAssertEqual(value.publishedTime, "2026-09-28")
        XCTAssertEqual(value.outputHTML, body["outputHTML"] as? String)
    }

    func testNestedRootNeedsAnOuterFrameOrFirstShadowRoot() {
        XCTAssertNil(NestedDOMRootSelector(layer0FrameSelector: nil, layer1ShadowRootSelector: nil,
                                           layer2ShadowRootSelector: ".inner"))
        XCTAssertNotNil(NestedDOMRootSelector(layer0FrameSelector: "iframe", layer1ShadowRootSelector: nil,
                                              layer2ShadowRootSelector: nil))
        XCTAssertNotNil(NestedDOMRootSelector(layer0FrameSelector: nil, layer1ShadowRootSelector: ".outer",
                                              layer2ShadowRootSelector: nil))
    }

    func testVideoRequiresBothURLStrings() {
        for key in ["pageURL", "windowURL"] {
            var body = urls
            body.removeValue(forKey: key)
            XCTAssertNil(VideoStatusMessage(body: body))
            for value in wrongStringValues {
                body = urls
                body[key] = value
                XCTAssertNil(VideoStatusMessage(body: body), key)
            }
        }
    }

    func testVideoWithoutCaptionListRemainsUsable() throws {
        for absent in [nil, NSNull(), "captions", 12] as [Any?] {
            var body = urls
            body["captionsOptions"] = absent
            body["providerVideoID"] = "movie-1"
            let value = try XCTUnwrap(VideoStatusMessage(body: body))
            XCTAssertTrue(value.captionsOptions.isEmpty)
            XCTAssertEqual(value.providerVideoID, "movie-1")
        }
    }

    func testMalformedCaptionEntriesDoNotDiscardOtherDictionaryEntries() throws {
        var invalid = caption
        invalid.removeValue(forKey: "label")
        var body = urls
        body["captionsOptions"] = [caption, invalid, caption]
        let value = try XCTUnwrap(VideoStatusMessage(body: body))
        XCTAssertEqual(value.captionsOptions.count, 2)
        XCTAssertEqual(value.captionsOptions.map(\.label), ["日本語", "日本語"])
        XCTAssertEqual(value.captionsOptions.first?.baseURL, URL(string: caption["baseURL"] as! String))
    }

    func testCaptionRequiresAllDeclaredFields() {
        for key in ["label", "languageCode", "kind", "isAutoGenerated", "baseURL"] {
            var body = caption
            body.removeValue(forKey: key)
            XCTAssertNil(VideoStatusMessage.CaptionsOption(dictionary: body), key)
            body[key] = NSNull()
            XCTAssertNil(VideoStatusMessage.CaptionsOption(dictionary: body), key)
        }
    }

    func testCaptionAcceptsOnlyActualBooleans() throws {
        for flag in [true, false] {
            var body = caption
            body["isAutoGenerated"] = flag
            XCTAssertEqual(try XCTUnwrap(VideoStatusMessage.CaptionsOption(dictionary: body)).isAutoGenerated, flag)
        }
        for flag in [0, 1, 0.0, 1.0, "true", "false", NSNull()] as [Any] {
            var body = caption
            body["isAutoGenerated"] = flag
            XCTAssertNil(VideoStatusMessage.CaptionsOption(dictionary: body))
        }
    }

    func testMetadataRequiresTitleAuthorAndURLStrings() {
        let valid: [String: Any] = ["title": "本", "author": "著者", "url": pageURL]
        for key in ["title", "author", "url"] {
            var body = valid
            body.removeValue(forKey: key)
            XCTAssertNil(PageMetadataUpdatedMessage(body: body), key)
            for value in wrongStringValues {
                body = valid
                body[key] = value
                XCTAssertNil(PageMetadataUpdatedMessage(body: body), key)
            }
        }
    }

    func testMetadataKeepsEmptyPresentAuthorAndExactTitle() throws {
        let value = try XCTUnwrap(PageMetadataUpdatedMessage(body: ["title": "  本 📖  ", "author": "", "url": pageURL]))
        XCTAssertEqual(value.title, "  本 📖  ")
        XCTAssertEqual(value.author, "")
        XCTAssertEqual(value.url, URL(string: pageURL))
    }

    func testDiagnosticRequiresStringSource() {
        XCTAssertNil(ReaderOnErrorMessage(body: [:]))
        for value in wrongStringValues { XCTAssertNil(ReaderOnErrorMessage(body: ["source": value])) }
    }

    func testDiagnosticPreservesMessageAndCoordinates() throws {
        let body: [String: Any] = ["source": pageURL, "message": "失敗", "error": "stack", "lineno": 10, "colno": 2]
        let value = try XCTUnwrap(ReaderOnErrorMessage(body: body))
        XCTAssertEqual(value.message, "失敗")
        XCTAssertEqual(value.error, "stack")
        XCTAssertEqual(value.source, URL(string: pageURL))
        XCTAssertEqual(value.lineno, 10)
        XCTAssertEqual(value.colno, 2)
        XCTAssertNil(value.documentStartedAtMilliseconds)
    }

    func testDiagnosticTimestampAcceptsNumericEndpointsAndFiniteMilliseconds() throws {
        for timestamp in [0.0, 1.0, 1_700_000_000_123.25] {
            let value = try XCTUnwrap(ReaderOnErrorMessage(body: ["source": pageURL, "documentStartedAtMs": timestamp]))
            XCTAssertEqual(value.documentStartedAtMilliseconds, timestamp)
        }
    }

    func testMalformedDiagnosticTimestampDoesNotDiscardTheError() throws {
        for timestamp in [true, false, "123", Double.nan, Double.infinity, -Double.infinity, NSNull(), []] as [Any] {
            let value = try XCTUnwrap(ReaderOnErrorMessage(body: ["source": pageURL, "documentStartedAtMs": timestamp]))
            XCTAssertNil(value.documentStartedAtMilliseconds)
        }
    }

    func testJSONRoundTripPreservesTypesInsteadOfCoercingValues() throws {
        let json = #"{"pageURL":"https://example.invalid/","windowURL":"https://example.invalid/","captionsOptions":[{"label":"ja","languageCode":"ja","kind":"captions","isAutoGenerated":false,"baseURL":"https://example.invalid/a"},{"label":"bad","languageCode":"ja","kind":"captions","isAutoGenerated":0,"baseURL":"https://example.invalid/b"}]}"#
        let body = try JSONSerialization.jsonObject(with: Data(json.utf8))
        XCTAssertEqual(try XCTUnwrap(VideoStatusMessage(body: body)).captionsOptions.map(\.label), ["ja"])
    }

    func testLongJapaneseContentHasNoNewArbitraryTruncation() throws {
        var body = readability
        let content = String(repeating: "<ruby>日本語<rt>にほんご</rt></ruby>", count: 5_000)
        body["content"] = content
        XCTAssertEqual(try XCTUnwrap(ReadabilityParsedMessage(body: body)).content, content)
    }
}
