import Foundation
import XCTest
@testable import LakeOfFireReader

final class ReaderJavascriptMessageDecodingTests: XCTestCase {
    func testReaderModeUnavailableRejectsMalformedRequiredURLFields() throws {
        XCTAssertNil(
            ReaderModeUnavailableMessage(
                body: ["windowURL": "https://example.com/article"]
            )
        )
        XCTAssertNil(
            ReaderModeUnavailableMessage(
                body: [
                    "pageURL": 42,
                    "windowURL": "https://example.com/article",
                ]
            )
        )

        let decoded = try XCTUnwrap(
            ReaderModeUnavailableMessage(
                body: [
                    "pageURL": "https://example.com/article#section",
                    "windowURL": "https://example.com/article",
                ]
            )
        )
        XCTAssertEqual(
            decoded.pageURL?.absoluteString,
            "https://example.com/article#section"
        )
        XCTAssertEqual(
            decoded.windowURL?.absoluteString,
            "https://example.com/article"
        )
    }

    func testReadabilityParsedRejectsEveryMalformedRequiredField() throws {
        let validBody: [String: Any] = [
            "pageURL": "https://example.com/article",
            "windowURL": "https://example.com/article",
            "title": "Article",
            "byline": "Author",
            "content": "<p>本文</p>",
            "inputHTML": "<main><p>本文</p></main>",
            "outputHTML": "<p>本文</p>",
        ]
        let requiredFields = [
            "pageURL",
            "windowURL",
            "title",
            "byline",
            "content",
            "inputHTML",
        ]

        for field in requiredFields {
            var body = validBody
            body[field] = NSNull()
            XCTAssertNil(
                ReadabilityParsedMessage(body: body),
                "Malformed \(field) must reject the entire payload"
            )
        }

        let decoded = try XCTUnwrap(ReadabilityParsedMessage(body: validBody))
        XCTAssertEqual(decoded.pageURL?.absoluteString, "https://example.com/article")
        XCTAssertEqual(decoded.windowURL?.absoluteString, "https://example.com/article")
        XCTAssertEqual(decoded.title, "Article")
        XCTAssertEqual(decoded.byline, "Author")
        XCTAssertEqual(decoded.content, "<p>本文</p>")
        XCTAssertEqual(decoded.inputHTML, "<main><p>本文</p></main>")
        XCTAssertEqual(decoded.outputHTML, "<p>本文</p>")
    }

    func testReadabilityParsedRetainsOptionalOutputHTMLDefault() throws {
        let decoded = try XCTUnwrap(
            ReadabilityParsedMessage(
                body: [
                    "pageURL": "https://example.com/article",
                    "windowURL": "https://example.com/article",
                    "title": "Article",
                    "byline": "",
                    "content": "<p>本文</p>",
                    "inputHTML": "<main><p>本文</p></main>",
                ]
            )
        )

        XCTAssertEqual(decoded.outputHTML, "")
    }

    func testVideoStatusRejectsMalformedRequiredURLFields() throws {
        let validBody: [String: Any] = [
            "pageURL": "https://example.com/watch",
            "windowURL": "https://example.com/watch",
            "providerVideoID": "video-1",
            "captionsOptions": [
                [
                    "label": "Japanese",
                    "languageCode": "ja",
                    "kind": "subtitles",
                    "isAutoGenerated": false,
                    "baseURL": "https://example.com/captions.vtt",
                ],
            ],
        ]

        var missingPageURL = validBody
        missingPageURL.removeValue(forKey: "pageURL")
        XCTAssertNil(VideoStatusMessage(body: missingPageURL))

        var wrongWindowURL = validBody
        wrongWindowURL["windowURL"] = 17
        XCTAssertNil(VideoStatusMessage(body: wrongWindowURL))

        let decoded = try XCTUnwrap(VideoStatusMessage(body: validBody))
        XCTAssertEqual(decoded.pageURL?.absoluteString, "https://example.com/watch")
        XCTAssertEqual(decoded.windowURL?.absoluteString, "https://example.com/watch")
        XCTAssertEqual(decoded.providerVideoID, "video-1")
        XCTAssertEqual(decoded.captionsOptions.count, 1)
        XCTAssertEqual(decoded.captionsOptions.first?.languageCode, "ja")
    }

    func testPageMetadataRejectsMalformedURLInsteadOfForceCasting() throws {
        XCTAssertNil(
            PageMetadataUpdatedMessage(
                body: [
                    "title": "Article",
                    "author": "Author",
                ]
            )
        )
        XCTAssertNil(
            PageMetadataUpdatedMessage(
                body: [
                    "title": "Article",
                    "author": "Author",
                    "url": 7,
                ]
            )
        )

        let decoded = try XCTUnwrap(
            PageMetadataUpdatedMessage(
                body: [
                    "title": "Article",
                    "author": "Author",
                    "url": "https://example.com/article",
                ]
            )
        )
        XCTAssertEqual(decoded.title, "Article")
        XCTAssertEqual(decoded.author, "Author")
        XCTAssertEqual(decoded.url?.absoluteString, "https://example.com/article")
    }

}
