import Foundation
import WebMedia

public typealias WebMediaWebScriptSet = WebMediaCaptureWebScriptSet
public typealias WebMediaWebScripts = WebMediaCaptureWebScripts
public typealias WebMediaWebMessageDecoder = WebMediaCaptureMessageDecoder
public typealias WebMediaCandidateSelector = WebMediaCaptureCandidateSelector
public typealias WebMediaRequestContextBuilder = WebMediaCaptureRequestContextBuilder
public typealias WebMediaScriptConfiguration = WebMediaCaptureScriptConfiguration
public typealias WebMediaResolutionMethod = WebMediaCaptureResolutionMethod
public typealias WebMediaPlaybackEvent = WebMediaCapturePlaybackEvent
public typealias WebMediaPlaybackEventName = WebMediaCapturePlaybackEventName
public typealias WebMediaPlaybackSnapshot = WebMediaCapturePlaybackSnapshot
public typealias WebMediaPlaybackPresentationMode = WebMediaCapturePlaybackPresentationMode
public typealias WebMediaPlaybackKind = WebMediaCapturePlaybackKind
public typealias WebMediaCandidate = WebMediaCaptureCandidate
public typealias WebMediaResolvedMedia = WebMediaCaptureResolvedMedia
public typealias WebMediaRequestContext = WebMediaCaptureRequestContext
public typealias WebMediaStorageScope = WebMediaCaptureStorageScope
public typealias WebMediaRetentionPolicy = WebMediaCaptureRetentionPolicy
public typealias WebMediaDownloadProgress = WebMediaCaptureDownloadProgress
public typealias OfflineWebMediaItem = WebMediaCaptureStoredMedia
public typealias OfflineWebMediaLibrary = WebMediaCaptureLibrary
public typealias DownloadedWebMedia = WebMediaCaptureDownloadedMedia
public typealias WebMediaDownloader = WebMediaCaptureDownloader
