import XCTest
@testable import LakeOfFireReader

final class ReaderWebMediaBridgeTests: XCTestCase {
    func testPreferredCaptionOptionUsesManualBeforeGeneratedFallbacks() throws {
        let options = [
            try makeCaption(languageCode: "ja", isAutoGenerated: true),
            try makeCaption(languageCode: "en-US", isAutoGenerated: false),
            try makeCaption(languageCode: "ja-JP", isAutoGenerated: true),
            try makeCaption(languageCode: "ja", isAutoGenerated: false),
        ]

        let preferred = try XCTUnwrap(
            ReaderWebMediaBridge.preferredCaptionOption(
                from: options,
                localeIdentifier: "ja-JP"
            )
        )

        XCTAssertEqual(preferred.languageCode, "ja")
        XCTAssertFalse(preferred.isAutoGenerated)
    }

    func testPreferredCaptionOptionUsesExactGeneratedBeforeSameLanguageGenerated() throws {
        let options = [
            try makeCaption(languageCode: "ja", isAutoGenerated: true),
            try makeCaption(languageCode: "ja-JP", isAutoGenerated: true),
        ]

        let preferred = try XCTUnwrap(
            ReaderWebMediaBridge.preferredCaptionOption(
                from: options,
                localeIdentifier: "ja-JP"
            )
        )

        XCTAssertEqual(preferred.languageCode, "ja-JP")
        XCTAssertTrue(preferred.isAutoGenerated)
    }

    private func makeCaption(
        languageCode: String,
        isAutoGenerated: Bool
    ) throws -> VideoStatusMessage.CaptionsOption {
        try XCTUnwrap(
            VideoStatusMessage.CaptionsOption(
                dictionary: [
                    "label": languageCode,
                    "languageCode": languageCode,
                    "kind": isAutoGenerated ? "asr" : "standard",
                    "isAutoGenerated": isAutoGenerated,
                    "baseURL": "https://example.com/\(languageCode).vtt",
                ]
            )
        )
    }
}
