import Foundation

/// Value payloads shared by WebKit delivery and direct decoding. Shape validation
/// is not document admission: consumers still own frame and write-lifetime checks.
public struct NestedDOMRootSelector: Sendable {
    public let layer0FrameSelector: String?
    public let layer1ShadowRootSelector: String?
    public let layer2ShadowRootSelector: String?

    public init?(layer0FrameSelector: String?, layer1ShadowRootSelector: String?, layer2ShadowRootSelector: String?) {
        guard layer1ShadowRootSelector != nil || layer0FrameSelector != nil else {
            return nil
        }
        self.layer0FrameSelector = layer0FrameSelector
        self.layer1ShadowRootSelector = layer1ShadowRootSelector
        self.layer2ShadowRootSelector = layer2ShadowRootSelector
    }
}

public struct ReaderOnErrorMessage: Sendable {
    public let message: String?
    public let source: URL
    public let lineno: Int?
    public let colno: Int?
    public let error: String?
    public let documentStartedAtMilliseconds: Double?

    public init?(body rawBody: Any?) {
        guard let body = rawBody as? [String: Any],
              let rawURL = body["source"] as? String,
              let url = URL(string: rawURL) else { return nil }
        message = body["message"] as? String
        source = url
        lineno = body["lineno"] as? Int
        colno = body["colno"] as? Int
        error = body["error"] as? String
        // Hotfix diagnostics remain usable without a timestamp. Never turn a
        // boolean or non-finite value into document provenance.
        documentStartedAtMilliseconds = ReaderMessagePayloadValue.number(body["documentStartedAtMs"])
    }
}

public struct ReaderModeUnavailableMessage: Sendable {
    public let pageURL: URL?
    public let windowURL: URL?

    public init?(body rawBody: Any?) {
        guard let body = rawBody as? [String: Any],
              let pageURLString = body["pageURL"] as? String,
              let windowURLString = body["windowURL"] as? String else { return nil }
        pageURL = URL(string: pageURLString)
        windowURL = URL(string: windowURLString)
    }
}

public struct ReadabilityParsedMessage: Sendable {
    public let pageURL: URL?
    public let windowURL: URL?
    public let readabilityContainerSelector: String?
    public let readabilityContainerRootSelector: NestedDOMRootSelector?
    public let title: String
    public let byline: String
    public let publishedTime: String?
    public let content: String
    public let inputHTML: String
    public let outputHTML: String

    public init?(body rawBody: Any?) {
        guard let body = rawBody as? [String: Any],
              let pageURLString = body["pageURL"] as? String,
              let windowURLString = body["windowURL"] as? String,
              let title = body["title"] as? String,
              let byline = body["byline"] as? String,
              let content = body["content"] as? String,
              let inputHTML = body["inputHTML"] as? String else { return nil }
        pageURL = URL(string: pageURLString)
        windowURL = URL(string: windowURLString)
        readabilityContainerSelector = body["readabilityContainerSelector"] as? String
        readabilityContainerRootSelector = NestedDOMRootSelector(
            layer0FrameSelector: body["layer0FrameSelector"] as? String,
            layer1ShadowRootSelector: body["layer1ShadowRootSelector"] as? String,
            layer2ShadowRootSelector: body["layer2ShadowRootSelector"] as? String)
        self.title = title
        self.byline = byline
        publishedTime = body["publishedTime"] as? String
        self.content = content
        self.inputHTML = inputHTML
        outputHTML = body["outputHTML"] as? String ?? ""
    }
}

public struct VideoStatusMessage: Sendable {
    public struct CaptionsOption: Sendable {
        public let label: String
        public let languageCode: String
        public let kind: String
        public let isAutoGenerated: Bool
        public let baseURL: URL

        init?(dictionary: [String: Any]) {
            guard let label = dictionary["label"] as? String,
                  let languageCode = dictionary["languageCode"] as? String,
                  let kind = dictionary["kind"] as? String,
                  let isAutoGenerated = ReaderMessagePayloadValue.boolean(dictionary["isAutoGenerated"]),
                  let baseURLString = dictionary["baseURL"] as? String,
                  let baseURL = URL(string: baseURLString) else {
                // Invalid page payloads can contain credential-bearing URLs.
                // Reject the entry without dumping the dictionary to the log.
                return nil
            }
            self.label = label
            self.languageCode = languageCode
            self.kind = kind
            self.isAutoGenerated = isAutoGenerated
            self.baseURL = baseURL
        }
    }

    public let windowURL: URL?
    public let pageURL: URL?
    public let providerVideoID: String?
    public let captionsOptions: [CaptionsOption]

    public init?(body rawBody: Any?) {
        guard let body = rawBody as? [String: Any],
              let pageURLString = body["pageURL"] as? String,
              let windowURLString = body["windowURL"] as? String else { return nil }
        pageURL = URL(string: pageURLString)
        windowURL = URL(string: windowURLString)
        providerVideoID = body["providerVideoID"] as? String
        if let captionsArray = body["captionsOptions"] as? [[String: Any]] {
            captionsOptions = captionsArray.compactMap { CaptionsOption(dictionary: $0) }
        } else {
            captionsOptions = []
        }
    }
}

public struct PageMetadataUpdatedMessage: Sendable {
    public let title: String
    public let author: String
    public let url: URL?

    public init?(body rawBody: Any?) {
        guard let body = rawBody as? [String: Any],
              let title = body["title"] as? String,
              let author = body["author"] as? String,
              let urlString = body["url"] as? String else { return nil }
        self.title = title
        self.author = author
        url = URL(string: urlString)
    }
}
