import Foundation
import LakeOfFireCore
import LakeOfFireContent

public enum ReaderCaptionAcquisitionError: Error, Sendable {
    case invalidProvenance
    case invalidEndpoint
    case disallowedRedirect
    case invalidResponse
    case httpStatus(Int)
    case responseTooLarge
}

/// Created only after the native bridge has admitted both the provider frame
/// and the resource's playback owner. It contains no page-supplied credentials.
public struct ReaderValidatedCaptionRequest: Sendable, Hashable {
    public let playbackOwner: ReaderMediaPlaybackOwner
    public let provider: String
    public let providerResourceID: String
    public let providerFrameURL: URL
    public let subtitleURL: URL
    public let languageIdentifier: String
    public let isAutoGenerated: Bool

    private init(playbackOwner: ReaderMediaPlaybackOwner, providerResourceID: String, providerFrameURL: URL, subtitleURL: URL, languageIdentifier: String, isAutoGenerated: Bool) {
        self.playbackOwner = playbackOwner
        self.provider = "youtube"
        self.providerResourceID = providerResourceID
        self.providerFrameURL = providerFrameURL
        self.subtitleURL = subtitleURL
        self.languageIdentifier = languageIdentifier
        self.isAutoGenerated = isAutoGenerated
    }

    static func youtube(playbackOwner: ReaderMediaPlaybackOwner, providerFrameURL: URL, claimedResourceID: String?, subtitleURL: URL, languageIdentifier: String, isAutoGenerated: Bool) -> Self? {
        guard let resourceID = ReaderMediaResourceIdentity.youtubeResourceID(from: providerFrameURL),
              resourceID == claimedResourceID,
              playbackOwner.resourceIdentity == ReaderMediaResourceIdentity.youtube(resourceID) else { return nil }
        let language = ReaderTranscriptLanguage.normalizedIdentifier(languageIdentifier)
        guard language != "und",
              let endpoint = canonicalEndpoint(subtitleURL, resourceID: resourceID, language: language, isAutoGenerated: isAutoGenerated) else { return nil }
        return Self(playbackOwner: playbackOwner, providerResourceID: resourceID, providerFrameURL: providerFrameURL, subtitleURL: endpoint, languageIdentifier: language, isAutoGenerated: isAutoGenerated)
    }

    func admits(_ url: URL) -> Bool {
        Self.canonicalEndpoint(url, resourceID: providerResourceID, language: languageIdentifier, isAutoGenerated: isAutoGenerated) == url
    }

    var request: URLRequest {
        var request = URLRequest(url: subtitleURL, cachePolicy: .reloadIgnoringLocalCacheData, timeoutInterval: 20)
        request.httpMethod = "GET"
        request.setValue("text/vtt", forHTTPHeaderField: "Accept")
        request.setValue(languageIdentifier, forHTTPHeaderField: "Accept-Language")
        request.setValue("https://www.youtube.com/watch?v=\(providerResourceID)", forHTTPHeaderField: "Referer")
        return request
    }

    private static func canonicalEndpoint(_ url: URL, resourceID: String, language: String, isAutoGenerated: Bool) -> URL? {
        guard url.absoluteString.utf8.count <= 16_384,
              url.scheme?.lowercased() == "https", url.user == nil, url.password == nil,
              url.fragment == nil, url.port == nil || url.port == 443,
              let host = url.host?.lowercased(),
              (["youtube.com", "www.youtube.com", "m.youtube.com"].contains(host) && url.path == "/api/timedtext")
                || (host == "video.google.com" && url.path == "/timedtext"),
              var components = URLComponents(url: url, resolvingAgainstBaseURL: false) else { return nil }
        let query = components.queryItems ?? []
        func unique(_ name: String) -> String? {
            let values = query.filter { $0.name == name }
            return values.count == 1 ? values[0].value : nil
        }
        guard unique("v") == resourceID,
              ReaderTranscriptLanguage.normalizedIdentifier(unique("lang")) == language,
              !query.contains(where: { $0.name.lowercased() == "tlang" }),
              query.filter({ $0.name == "fmt" }).count <= 1,
              query.filter({ $0.name == "kind" }).count <= 1,
              (unique("kind") == "asr") == isAutoGenerated else { return nil }
        components.queryItems = query.filter { $0.name != "fmt" } + [URLQueryItem(name: "fmt", value: "vtt")]
        return components.url
    }
}

public struct ReaderAcquiredCaption: Sendable {
    public let webVTT: String
    public let languageIdentifier: String
    public let playbackOwner: ReaderMediaPlaybackOwner
    public let provider: String
    public let providerResourceID: String
    public let isAutoGenerated: Bool
}

public enum ReaderCaptionAcquisition {
    public static func fetch(_ request: ReaderValidatedCaptionRequest) async throws -> ReaderAcquiredCaption {
        try Task.checkCancellation()
        let transfer = CaptionTransfer(request: request)
        let data = try await withTaskCancellationHandler {
            try await withCheckedThrowingContinuation { continuation in
                transfer.start(continuation)
            }
        } onCancel: {
            transfer.cancel()
        }
        try Task.checkCancellation()
        let document = try ReaderTranscriptDocument(data: data)
        return ReaderAcquiredCaption(webVTT: document.webVTT, languageIdentifier: request.languageIdentifier, playbackOwner: request.playbackOwner, provider: request.provider, providerResourceID: request.providerResourceID, isAutoGenerated: request.isAutoGenerated)
    }

    public static func fetch(request: ReaderValidatedCaptionRequest) async throws -> ReaderAcquiredCaption {
        try await fetch(request)
    }
}

/// Delegate callbacks, continuation installation, and cancellation share one
/// serial lifecycle queue. All terminal paths resume the waiter exactly once.
private final class CaptionTransfer: NSObject, URLSessionDataDelegate, @unchecked Sendable {
    private let admitted: ReaderValidatedCaptionRequest
    private let queue: OperationQueue = {
        let queue = OperationQueue()
        queue.name = "ReaderCaptionAcquisition"
        queue.maxConcurrentOperationCount = 1
        return queue
    }()
    private var continuation: CheckedContinuation<Data, Error>?
    private var session: URLSession?
    private var task: URLSessionDataTask?
    private var data = Data()
    private var cancelled = false
    private var finished = false
    private var admittedResponse = false
    private var redirectCount = 0

    init(request: ReaderValidatedCaptionRequest) {
        admitted = request
        super.init()
    }

    func start(_ continuation: CheckedContinuation<Data, Error>) {
        queue.addOperation { [self] in
            self.continuation = continuation
            guard !cancelled else { finish(.failure(CancellationError())); return }
            let configuration = URLSessionConfiguration.ephemeral
            configuration.httpShouldSetCookies = false
            configuration.httpCookieStorage = nil
            configuration.urlCredentialStorage = nil
            configuration.urlCache = nil
            configuration.timeoutIntervalForRequest = 20
            configuration.timeoutIntervalForResource = 45
            let session = URLSession(configuration: configuration, delegate: self, delegateQueue: queue)
            self.session = session
            let task = session.dataTask(with: admitted.request)
            self.task = task
            task.resume()
        }
    }

    func cancel() {
        queue.addOperation { [self] in
            cancelled = true
            if continuation != nil { finish(.failure(CancellationError())) }
        }
    }

    private func finish(_ result: Result<Data, Error>) {
        guard !finished, let continuation else { return }
        finished = true
        self.continuation = nil
        task?.cancel()
        task = nil
        session?.invalidateAndCancel()
        session = nil
        data.removeAll(keepingCapacity: false)
        continuation.resume(with: result)
    }

    func urlSession(_ session: URLSession, task: URLSessionTask, willPerformHTTPRedirection response: HTTPURLResponse, newRequest request: URLRequest, completionHandler: @escaping (URLRequest?) -> Void) {
        guard !finished, !cancelled, redirectCount < 3, let url = request.url, admitted.admits(url) else {
            completionHandler(nil)
            finish(.failure(ReaderCaptionAcquisitionError.disallowedRedirect))
            return
        }
        redirectCount += 1
        var next = admitted.request
        next.url = url
        completionHandler(next)
    }

    func urlSession(_ session: URLSession, dataTask: URLSessionDataTask, didReceive response: URLResponse, completionHandler: @escaping (URLSession.ResponseDisposition) -> Void) {
        guard !finished, let http = response as? HTTPURLResponse, let url = http.url, admitted.admits(url) else {
            completionHandler(.cancel)
            finish(.failure(ReaderCaptionAcquisitionError.invalidResponse))
            return
        }
        guard http.statusCode == 200 else {
            completionHandler(.cancel)
            finish(.failure(ReaderCaptionAcquisitionError.httpStatus(http.statusCode)))
            return
        }
        guard ["text/vtt", "text/plain", "application/octet-stream"].contains(http.mimeType?.lowercased() ?? ""),
              http.expectedContentLength <= Int64(ReaderTranscriptDocument.maximumBytes) else {
            completionHandler(.cancel)
            finish(.failure(ReaderCaptionAcquisitionError.invalidResponse))
            return
        }
        admittedResponse = true
        completionHandler(.allow)
    }

    func urlSession(_ session: URLSession, dataTask: URLSessionDataTask, didReceive chunk: Data) {
        guard !finished else { return }
        guard admittedResponse, chunk.count <= ReaderTranscriptDocument.maximumBytes - data.count else {
            finish(.failure(ReaderCaptionAcquisitionError.responseTooLarge))
            return
        }
        data.append(chunk)
    }

    func urlSession(_ session: URLSession, task: URLSessionTask, didCompleteWithError error: Error?) {
        guard !finished else { return }
        if let error { finish(.failure(error)) }
        else if admittedResponse { finish(.success(data)) }
        else { finish(.failure(ReaderCaptionAcquisitionError.invalidResponse)) }
    }
}
